-- follow below step to upload bulk data via command prompt.

-- Step 1 - cd C:\Program Files\MySQL\MySQL Server 8.0\bin  -- run this command
-- Step 2 - mysql -u root -p --local-infile=1               -- run this command then enter password
-- Step 3 - SHOW GLOBAL VARIABLES LIKE 'local_infile';      -- run this command to check local_infile ststus if OFF
-- Step 4 - SET GLOBAL local_infile = 1;                    -- run this command to set  local_infile ststus ON
-- Step 5 - SHOW GLOBAL VARIABLES LIKE 'local_infile';      -- run this command to check local_infile ststus if it is ON or not
-- Step 6 - Create database h1b_visa;                       -- run this command to create database
-- Step 7 - use h1b_visa;                                   -- run this command to use database
/* Step 8 - 
CREATE TABLE h1b_data (                         -- run this data in command promp to create table h1b_data
CASE_NUMBER TEXT ,
CASE_STATUS TEXT ,
RECEIVED_DATE VARCHAR(25) ,
DECISION_DATE VARCHAR(25) ,
ORIGINAL_CERT_DATE VARCHAR(25) ,
VISA_CLASS TEXT ,
JOB_TITLE TEXT ,
SOC_CODE TEXT ,
SOC_TITLE TEXT ,
FULL_TIME_POSITION TEXT ,
BEGIN_DATE VARCHAR(25) ,
END_DATE VARCHAR(25) ,
TOTAL_WORKER_POSITIONS INT ,
NEW_EMPLOYMENT INT ,
CONTINUED_EMPLOYMENT INT ,
CHANGE_PREVIOUS_EMPLOYMENT INT ,
NEW_CONCURRENT_EMPLOYMENT INT ,
CHANGE_EMPLOYER INT ,
AMENDED_PETITION INT ,
EMPLOYER_NAME TEXT ,
TRADE_NAME_DBA TEXT,
EMPLOYER_ADDRESS1 TEXT ,
EMPLOYER_ADDRESS2 TEXT,
EMPLOYER_CITY TEXT ,
EMPLOYER_STATE TEXT ,
EMPLOYER_POSTAL_CODE TEXT ,
EMPLOYER_COUNTRY TEXT ,
EMPLOYER_PROVINCE TEXT,
EMPLOYER_PHONE TEXT ,
EMPLOYER_PHONE_EXT FLOAT,
NAICS_CODE INT ,
EMPLOYER_POC_LAST_NAME TEXT ,
EMPLOYER_POC_FIRST_NAME TEXT ,
EMPLOYER_POC_MIDDLE_NAME TEXT,
EMPLOYER_POC_JOB_TITLE TEXT ,
EMPLOYER_POC_ADDRESS1 TEXT ,
EMPLOYER_POC_ADDRESS2 TEXT,
EMPLOYER_POC_CITY TEXT ,
EMPLOYER_POC_STATE TEXT ,
EMPLOYER_POC_POSTAL_CODE TEXT ,
EMPLOYER_POC_COUNTRY TEXT ,
EMPLOYER_POC_PROVINCE TEXT,
EMPLOYER_POC_PHONE TEXT ,
EMPLOYER_POC_PHONE_EXT FLOAT,
EMPLOYER_POC_EMAIL TEXT,
AGENT_REPRESENTING_EMPLOYER TEXT ,
AGENT_ATTORNEY_LAST_NAME TEXT,
AGENT_ATTORNEY_FIRST_NAME TEXT,
AGENT_ATTORNEY_MIDDLE_NAME TEXT,
AGENT_ATTORNEY_ADDRESS1 TEXT,
AGENT_ATTORNEY_ADDRESS2 TEXT,
AGENT_ATTORNEY_CITY TEXT,
AGENT_ATTORNEY_STATE TEXT,
AGENT_ATTORNEY_POSTAL_CODE TEXT,
AGENT_ATTORNEY_COUNTRY TEXT,
AGENT_ATTORNEY_PROVINCE TEXT,
AGENT_ATTORNEY_PHONE TEXT,
AGENT_ATTORNEY_PHONE_EXT FLOAT,
AGENT_ATTORNEY_EMAIL_ADDRESS TEXT,
LAWFIRM_NAME_BUSINESS_NAME TEXT,
STATE_OF_HIGHEST_COURT TEXT,
NAME_OF_HIGHEST_STATE_COURT TEXT,
WORKSITE_WORKERS INT ,
SECONDARY_ENTITY TEXT ,
SECONDARY_ENTITY_BUSINESS_NAME TEXT,
WORKSITE_ADDRESS1 TEXT ,
WORKSITE_ADDRESS2 TEXT,
WORKSITE_CITY TEXT ,
WORKSITE_COUNTY TEXT ,
WORKSITE_STATE TEXT ,
WORKSITE_POSTAL_CODE TEXT ,
WAGE_RATE_OF_PAY_FROM TEXT ,
WAGE_RATE_OF_PAY_TO TEXT,
WAGE_UNIT_OF_PAY TEXT ,
PREVAILING_WAGE TEXT ,
PW_UNIT_OF_PAY TEXT ,
PW_TRACKING_NUMBER TEXT,
PW_WAGE_LEVEL TEXT,
PW_OES_YEAR TEXT,
PW_OTHER_SOURCE TEXT,
PW_OTHER_YEAR TEXT,
PW_SURVEY_PUBLISHER TEXT,
PW_SURVEY_NAME TEXT,
TOTAL_WORKSITE_LOCATIONS TEXT,
AGREE_TO_LC_STATEMENT TEXT ,
H_1B_DEPENDENT TEXT,
WILLFUL_VIOLATOR TEXT,
SUPPORT_H1B TEXT,
STATUTORY_BASIS TEXT,
APPENDIX_A_ATTACHED TEXT,
PUBLIC_DISCLOSURE TEXT,
PREPARER_LAST_NAME TEXT,
PREPARER_FIRST_NAME TEXT,
PREPARER_MIDDLE_INITIAL TEXT,
PREPARER_BUSINESS_NAME TEXT,
PREPARER_EMAIL TEXT) ;
*/
-- Step 9 - Show table;                                                   -- run this command to check table status

/*
Step 10 - LOAD DATA LOCAL INFILE 'E:\LCA_Disclosure_Data_FY2023_Q1.csv' 
INTO TABLE h1b_data FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 ROWS;       -- run this to load FY2023_Q1 into table
 
Step 11 - LOAD DATA LOCAL INFILE 'E:\LCA_Disclosure_Data_FY2023_Q2.csv' 
INTO TABLE h1b_data FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 ROWS;        -- run this to load FY2023_Q1 into table

Step 12 -LOAD DATA LOCAL INFILE 'E:\LCA_Disclosure_Data_FY2023_Q3.csv' 
INTO TABLE h1b_data FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 ROWS;        -- run this to load FY2023_Q1 into table
 
Step 13 - LOAD DATA LOCAL INFILE 'E:\LCA_Disclosure_Data_FY2023_Q4.csv' 
INTO TABLE h1b_data FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 ROWS;        -- run this to load FY2023_Q1 into table 
*/

-- use databse 
use h1b_visa;     

-- CHEKCING THE COUNT OF ROWS
SELECT COUNT(*) FROM H1B_DATA;

-- CHECK DATA VALUES
SELECT * FROM H1B_DATA LIMIT 5;

-- CHECK DATA TYPE
DESCRIBE H1B_DATA;

-- CONVERT THE DATA TYPE AND VALUE OF WAGE COLUMN 
-- WAGE_RATE_OF_PAY_FROM
update h1b_data set WAGE_RATE_OF_PAY_FROM = case
when WAGE_RATE_OF_PAY_FROM = "" then Null else
cast(replace(replace(WAGE_RATE_OF_PAY_FROM, '$' , ""), ",", "") as decimal(10,2))
end;

-- WAGE_RATE_OF_PAY_TO
update h1b_data set WAGE_RATE_OF_PAY_TO = case
when WAGE_RATE_OF_PAY_TO = "" then Null else
cast(replace(replace(WAGE_RATE_OF_PAY_TO, '$' , ""), ",", "") as decimal(10,2))
end;


-- PREVAILING_WAGE
update h1b_data set PREVAILING_WAGE = case
when PREVAILING_WAGE = "" then Null else
cast(replace(replace(PREVAILING_WAGE, '$' , ""), ",", "") as decimal(10,2))
end;

-- CONVERTING DATA VALUES AND DATA TYPES IN CORRECT FORMAT
UPDATE H1B_DATA
SET RECEIVED_DATE = STR_TO_DATE(RECEIVED_DATE , '%d-%m-%Y');

UPDATE H1B_DATA
SET DECISION_DATE = STR_TO_DATE(DECISION_DATE , '%m/%d/%Y');
UPDATE H1B_DATA
SET BEGIN_DATE = STR_TO_DATE(BEGIN_DATE , '%m/%d/%Y');
UPDATE H1B_DATA
SET END_DATE = STR_TO_DATE(END_DATE , '%m/%d/%Y');


SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
SET innodb_lock_wait_timeout = 120; -- Set the timeout value in seconds
SHOW VARIABLES LIKE 'wait_timeout';
SHOW VARIABLES LIKE 'interactive_timeout';
SET SESSION wait_timeout = 300;
SET SESSION interactive_timeout = 300;
SET GLOBAL wait_timeout = 300;
SET GLOBAL interactive_timeout = 300;
SET GLOBAL max_allowed_packet = 32 * 1024 * 1024;

-- Null value in table




select case_number, case when  WAGE_RATE_OF_PAY_FROM is null then 
1 end from h1b_data;

-- Check Duplicate 

